services:
  - type: cron
    name: fb-alert
    env: python
    schedule: "*/15 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: FB_SESSION_COOKIE
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
